name: Release

on:
  push:
    branches:
      - "master"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: 1.1.8
      - name: Install Dependencies
        run: |
          poetry install
      - name: Run Lints
        run: |
          poetry run black -v --check .
          poetry run flake8 -v --ignore=E501,W503,E722
      - name: Run Tests
        run: |
          poetry run pytest -v
      - name: Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN_PROD }}
